cargo-features = ["edition"]
[package]
edition = "2018"
authors = ["Pascal Seitz <pascal.seitz@gmail.com>"]
name = "parser"
version = "0.1.0"

[dependencies]
combine = "3.6.3"

[[bench]]
name = "bench"
path = "bench/bench.rs"